/* eslint-disable no-inner-declarations */
import obPlugin from "./scripts/ob.esbuild.mjs";
import { inlineWorkerPlugin } from "@aidenlx/esbuild-plugin-inline-worker";
import { Octokit } from "@octokit/rest";
import { execFileSync } from "child_process";
import { build, context } from "esbuild";
import { lessLoader } from "esbuild-plugin-less";
import { readFile } from "fs/promises";
import { join } from "path";
// import myPackage from "./package.json" assert { type: "json" };
import semverPrerelease from "semver/functions/prerelease.js";
// Read the ACTUALLY-RESOLVED better-sqlite3 package version from node_modules.
// This is the JS code esbuild is about to bundle into main.js; WiseLibs
// publishes GitHub release tags + prebuilt .tar.gz filenames in lockstep with
// the npm version, so this string is guaranteed to match the download URL.
// Reading the resolved package (not our own package.json spec) means caret
// ranges, workspace protocols, and transitive resolutions all "just work".
import betterSqlite3Pkg from "better-sqlite3/package.json" with { type: "json" };
import PostcssPlugin from "./esbuild-postcss.mjs";

const myPackage = JSON.parse(await readFile("./package.json"));
const isPreRelease = semverPrerelease(myPackage.version) !== null;

const isProd = process.env?.BUILD === "production";

const git = (args, fallback = "") => {
  try {
    return execFileSync("git", args, { encoding: "utf8" }).trim();
  } catch {
    return fallback;
  }
};

const remoteUrl = git(
  ["remote", "get-url", "origin"],
  "https://github.com/Ascarshen/obsidian-zotlit.git",
);
const remoteMatch = remoteUrl.match(/github\.com[:/]([^/]+)\/([^/.]+)(?:\.git)?$/);
const repoPath = remoteMatch
  ? `${remoteMatch[1]}/${remoteMatch[2]}`
  : "Ascarshen/obsidian-zotlit";
const patchedBuildCommit = git(["rev-parse", "--short", "HEAD"], "unknown");
const patchedBuildRepoUrl = `https://github.com/${repoPath}`;
const patchedBuildReleaseUrl = `${patchedBuildRepoUrl}/releases/latest`;
const patchedBuildLatestApiUrl = `https://api.github.com/repos/${repoPath}/releases/latest`;

// In PROD only: fetch the WiseLibs release for the resolved version and derive
// a { [modules]: { [platform]: arch[] } } support matrix from its prebuilt
// asset filenames. This replaces the hand-maintained app/obsidian/src/platform.json.
// Fails the build on any error — Octokit throws on non-2xx, and we also throw
// if the asset-name parse produces an empty matrix. We never ship a bundle
// whose runtime platform check runs against absent/stale data.
//
// In DEV: skip the fetch entirely. Inject an empty matrix {} — the runtime
// helpers treat that as "skip the pre-flight, trust the download" and fall
// through to the existing 404-fallback in guide/auto.tsx.
const betterSqlite3SupportMatrix = isProd
  ? await (async () => {
      const releaseTag = `v${betterSqlite3Pkg.version}`;
      const octokit = new Octokit({
        auth: process.env.GITHUB_TOKEN, // undefined = unauthenticated, 60/hr
        userAgent: "zotlit-build",
      });
      const { data: release } = await octokit.repos.getReleaseByTag({
        owner: "WiseLibs",
        repo: "better-sqlite3",
        tag: releaseTag,
      });
      const assetRe = new RegExp(
        `^better-sqlite3-${releaseTag}-electron-v(\\d+)-([^-]+)-([^.]+)\\.tar\\.gz$`,
      );
      const matrix = {};
      for (const asset of release.assets) {
        const m = asset.name.match(assetRe);
        if (!m) continue;
        const [, modules, platform, arch] = m;
        ((matrix[modules] ??= {})[platform] ??= []).push(arch);
      }
      if (Object.keys(matrix).length === 0) {
        throw new Error(
          `WiseLibs release ${releaseTag} has no electron prebuilt assets — ` +
            `either the version is wrong or WiseLibs changed their asset naming convention`,
        );
      }
      console.log(
        `better-sqlite3 ${releaseTag} prebuilt electron releases:`,
      );
      for (const [modules, platforms] of Object.entries(matrix)) {
        for (const [platform, archs] of Object.entries(platforms)) {
          console.log(`  modules=${modules} ${platform}: ${archs.join(", ")}`);
        }
      }
      return matrix;
    })()
  : {};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository
*/
`;

const cmExternals = [
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/text",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/lr",
  "@lezer/highlight",
  "@codemirror/closebrackets",
  "@codemirror/comment",
  "@codemirror/fold",
  "@codemirror/gutter",
  "@codemirror/highlight",
  "@codemirror/history",
  "@codemirror/matchbrackets",
  "@codemirror/panel",
  "@codemirror/rangeset",
  "@codemirror/rectangular-selection",
  "@codemirror/stream-parser",
  "@codemirror/tooltip",
];

const preactCompatPlugin = {
  name: "preact-compat",
  setup(build) {
    const preact = join(process.cwd(), "node_modules", "@preact", "compat");
    build.onResolve({ filter: /^(react-dom|react)$/ }, () => {
      return { path: join(preact, "index.mjs") };
    });
    build.onResolve({ filter: /^react\/jsx-runtime$/ }, () => {
      return { path: join(preact, "jsx-runtime.mjs") };
    });
  },
};

/** @type import("esbuild").BuildOptions */
const baseOpts = {
  bundle: true,
  platform: "node",
  format: "cjs",
  mainFields: ["browser", "module", "main"],
  minify: isProd,
  define: {
    "process.env.NODE_ENV": JSON.stringify(process.env.BUILD ?? ""),
    "process.env.SQL_VERBOSE": JSON.stringify(process.env.SQL_VERBOSE ?? ""),
    "process.env.BETTER_SQLITE3_VERSION": JSON.stringify(
      betterSqlite3Pkg.version,
    ),
    // Top-level identifier (NOT process.env.*) — matrix is an object, so a
    // single JSON.stringify inlines it as a JS object literal at call sites.
    // No runtime JSON.parse, no casts; type comes from `declare const` in env.d.ts.
    BETTER_SQLITE3_SUPPORT: JSON.stringify(betterSqlite3SupportMatrix),
    PATCHED_BUILD_COMMIT: JSON.stringify(patchedBuildCommit),
    PATCHED_BUILD_REPO_URL: JSON.stringify(patchedBuildRepoUrl),
    PATCHED_BUILD_RELEASE_URL: JSON.stringify(patchedBuildReleaseUrl),
    PATCHED_BUILD_LATEST_API_URL: JSON.stringify(patchedBuildLatestApiUrl),
  },
};

/** @type import("esbuild").BuildOptions */
const opts = {
  ...baseOpts,
  logLevel: process.env.BUILD === "development" ? "info" : "silent",
  external: ["obsidian", "electron", "@electron/remote", ...cmExternals],
  mainFields: ["browser", "module", "main"],
  sourcemap: isProd ? false : "inline",
  loader: {
    ".svg": "text",
    ".ejs": "text",
  },
  entryPoints: ["src/zt-main.ts"],
  banner: { js: banner },
  outfile: "build/main.js",
  tsconfig: "tsconfig.build.json",
  plugins: [
    lessLoader(),
    obPlugin({ beta: isPreRelease }),
    preactCompatPlugin,
    inlineWorkerPlugin({
      buildOptions: async ({ path }, resolve) => ({
        ...baseOpts,
        tsconfig: (
          await resolve(
            path.startsWith("@/worker-web/")
              ? "src/worker-web/tsconfig.json"
              : path.startsWith("@/worker-iframe/")
              ? "src/worker-iframe/tsconfig.json"
              : `${path}/tsconfig`,
            { kind: "require-resolve" }
          )
        ).path,
        target: "es2022",
        platform: path.startsWith("@/worker-iframe/") ? "browser": "node",
        format: path.startsWith("@/worker-iframe/") ? "esm" : "cjs",
        sourcemap: !isProd ? "inline" : false,
      }),
      cachedir: "dist",
      watch: !isProd,
    }),
    PostcssPlugin({}),
  ],
};

if (!isProd) {
  const ctx = await context({ ...opts, logLevel: "error" });
  try {
    await ctx.watch();
  } catch (err) {
    console.error(err);
    await cleanup();
  }
  process.on("SIGINT", cleanup);
  async function cleanup() {
    await ctx.dispose();
    // scheduleOnDisposeCallbacks defer function calls using setTimeout(...,0)
    // so we need to wait a bit before exiting
    // setTimeout(() => process.exit(), 100);
  }
} else {
  await build(opts);
}
